spring:
  profiles:
    active: dev
    include: secret
  security:
    oauth2:
      client:
        registration:
          kakao:
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost
    port: 6379
  batch:
    job:
      names: ${job.name:NONE}

custom:
  socket:
    path: '/sub/alarm/'
    alarm_type_notification: 'NOTIFICATION'
    alarm_type_chat: 'CHAT'
  redis:
    item:
      bidding:
        info-key: 'bidding-item:'
        item-count-buffer: 'item-count-buffer'
        count-suffix: 'Count'

springdoc:
  swagger-ui:
    path: /swagger-ui.html        # Swagger UI 경로 => localhost:8080/swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
