spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: 127.0.0.1
    port: 6379
custom:
  redis:
    item_queue: 'ITEM_TEST_QUEUE:'