spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          kakao:
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
            clientId: '0604c0cada4293ab7d8f98999c83c35e'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  batch:
    job:
      names: ${job.name:NONE}

  cache:
    type: redis
    redis:
      cache-null-values: true # null 캐싱 여부
      host: localhost
      port: 6379

custom:
  socket:
    path: '/sub/alarm/'
    alarm_type_notification: 'NOTIFICATION'
    alarm_type_chat: 'CHAT'
  redis:
    item_queue: 'ITEM_QUEUE:'
