spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/bidder_own?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
#    username: leui
#    password: 1234
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
