name: bidderown leui server CI/CD

on:
  push:
    branches:
      - main-leui

env:
  S3_BUCKET_NAME: leuibucket
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: application-secret.yml 파일 생성
        run: touch ./src/main/resources/application-secret.yml
        
      - name: application-secret.yml 복사
        run: echo "${{ secrets.APPLICATION_SECRET_LEUI }}" > src/main/resources/application-secret.yml
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17' 
          distribution: 'temurin'
          
      - name: Grant execute permisson for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew clean build
        
      - name: Make Directory
        run: mkdir -p deploy
      
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy
      
      - name: Make zip file
        run: zip -r ./bidderownserver.zip ./deploy
        shell: bash
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./bidderownserver.zip s3://$S3_BUCKET_NAME/
